src/main/java/hu/firstvan/model/Issue.java
package hu.firstvan.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.List;


@JsonIgnoreProperties(ignoreUnknown = true)
public class Issue {
    private String key;
    private String self;
    private Fields fields;

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getSelf() {
        return self;
    }

    public void setSelf(String self) {
        this.self = self;
    }

    public Fields getFields() {
        return fields;
    }

    public void setFields(Fields fields) {
        this.fields = fields;
    }
}

src/main/java/hu/firstvan/model/Worklog.java
package hu.firstvan.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import hu.firstvan.controller.DateUtil;

import java.util.Date;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Worklog {
    private Long id;
    private Author author;
    private Date created;
    private Date updated;
    private Date started;
    private String timeSpent;
    private String timeSpentSeconds;
    private String comment;

    public Worklog() {
    }

    public Author getAuthor() {
        return author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

    public Date getCreated() {
        return DateUtil.getNormalDate(created);
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getUpdated() {
        return DateUtil.getNormalDate(updated);
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    public Date getStarted() {
        return started;
    }

    public Date getStartedWithoutNormalize() {
        return started;
    }

    public void setStarted(Date started) {
        this.started = started;
    }

    public String getTimeSpent() {
        return timeSpent;
    }

    public void setTimeSpent(String timeSpent) {
        this.timeSpent = timeSpent;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTimeSpentSeconds() {
        return timeSpentSeconds;
    }

    public void setTimeSpentSeconds(String timeSpentSeconds) {
        this.timeSpentSeconds = timeSpentSeconds;
    }
}

src/main/java/hu/firstvan/controller/IssueBean.java
package hu.firstvan.controller;

import hu.firstvan.client.IssueFromJira;
import hu.firstvan.model.Issue;
import hu.firstvan.model.Worklog;

import javax.ejb.Stateless;
import javax.inject.Inject;
import java.util.List;

@Stateless
public class IssueBean {

    @Inject
    private IssueFromJira issueFromJira;

    public List<Issue> getUsedIssueByUser(final String username) {
        return issueFromJira.getLoggedInUserIssues(username);
    }

    public Issue getIssueByKey(final String username, final String key) {
        return issueFromJira.getIssueByKey(username, key);
    }

    public Worklog getWorklogByKey(final String username, final String issueId, final String worklogId) {
        return issueFromJira.getWorklogById(username, issueId, worklogId);
    }

    public int modifyWorklog(final String username, final String issueId, final Worklog worklog) {
        return issueFromJira.modifyWorklog(username, issueId, worklog);
    }

    public int createWorklog(final String username, final String issueId, final Worklog worklog) {
        return issueFromJira.createWorklog(username, issueId, worklog);
    }

    public String getWorklogSummaryByDateAndUser(final String username, final String date,
                                              final String user, final String token) {
        return issueFromJira.getWorklogSummaryByDateAndUser(username, date, user, token);
    }
}

src/main/webapp/views/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/default.xhtml">
    <ui:define name="content">

        <div class="jumbotron">
            <h2 class="display-4">Főoldal</h2>
        </div>

        <h:form id="searchPanel">
            <div class="searchBorder">
                <div class="form-group row justify-content-center">
                    <label for="inputKey" class="col-sm-3 col-form-label">Issue kulcs:</label>
                    <div class="col-sm-5">
                        <p:inputText styleClass="form-control" id="inputKey" value="#{indexView.issueKey}" />
                    </div>
                </div>
                <div class="form-group row justify-content-center">
                    <div>
                        <p:commandButton value="Keresés" styleClass="btn btn-primary" id="startSearch" upldate="@form"
                                         actionListener="#{indexView.searchIssue}" process="searchPanel" ajax="false"/>
                    </div>
                </div>
            </div>

            <p:dataTable id="issueTable" var="issue" value="#{indexView.issues}"  rows="10"
                            paginator="true"
                            paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                            rowsPerPageTemplate="10,20,50">
                <p:column headerText="Id">
                    <p:link outcome="/views/issue" value="#{issue.key}">
                        <f:param name="issueId" value="#{issue.key}" />
                    </p:link>
                </p:column>
                <p:column headerText="Név">
                    <h:outputText value="#{issue.fields.summary}" />
                </p:column>
                <p:column headerText="Módosítva">
                    <h:outputText value="#{issue.fields.updated}">
                        <f:convertDateTime pattern="yyyy.MM.dd HH:mm" />
                    </h:outputText>
                </p:column>
                <p:column headerText="Státusz">
                    <h:outputText value="#{issue.fields.status.name}" />
                </p:column>
            </p:dataTable>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/views/issue.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/default.xhtml">
    <ui:define name="content">

        <div class="jumbotron">
            <h2 class="display-4">Feladat részletei</h2>
        </div>

            <div style="padding-left: 15px; padding-right: 15px;">
                <div class="row row-border">
                    <div class="col-3">
                        Kulcs:
                    </div>
                    <div class="col">
                        #{issueView.issue.key}
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Név:
                    </div>
                    <div class="col">
                        #{issueView.issue.fields.summary}
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Leírás:
                    </div>
                    <div class="col">
                        #{issueView.issue.fields.description}
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Státusz:
                    </div>
                    <div class="col">
                        #{issueView.issue.fields.status.name}
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Módosítva:
                    </div>
                    <div class="col">
                        <h:outputText value="#{issueView.issue.fields.updated}">
                            <f:convertDateTime pattern="yyyy.MM.dd HH:mm" />
                        </h:outputText>
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Projekt:
                    </div>
                    <div class="col">
                        #{issueView.issue.fields.project.name}
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Módosítva:
                    </div>
                    <div class="col">
                        <h:outputText value="#{issueView.issue.fields.created}">
                            <f:convertDateTime pattern="yyyy.MM.dd HH:mm" />
                        </h:outputText>
                    </div>
                </div>
            </div>

            <h:form id="searchPanel">
                <div class="searchBorder" style="margin-top: 20px;">
                    <div class="form-group row justify-content-center">
                        <label for="c1" class="col-sm-3 col-form-label">Keresett nap:</label>
                        <div class="col-sm-5">
                            <h:panelGroup>
                                <p:calendar id="c1" pattern="yyyy/MM/dd" timeZone="IST"
                                        value="#{issueView.searchDate}" showOn="button"/>
                            </h:panelGroup>
                        </div>
                    </div>
                    <div class="form-group row justify-content-center">
                        <div>
                            <p:commandButton value="Keresés" styleClass="btn btn-primary" id="startSearch" upldate="@form"
                                             actionListener="#{issueView.changeDay}" process="searchPanel" ajax="false"/>
                        </div>
                    </div>
                </div>

                <p:dataTable var="worklog" value="#{issueView.worklogs}"  rows="10"
                             paginator="true"
                             paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="10,20,50" style="padding-top: 50px;">
                    <p:column headerText="Szerző">
                        <p:link outcome="/views/worklog" value="#{worklog.author.name}">
                            <f:param name="issueId" value="#{issueView.issue.key}" />
                            <f:param name="worklogId" value="#{worklog.id}" />
                        </p:link>
                    </p:column>
                    <p:column headerText="Kezdés">
                        <h:outputText value="#{worklog.startedWithoutNormalize}">
                            <f:convertDateTime pattern="yyyy.MM.dd HH:mm" />
                        </h:outputText>
                    </p:column>
                    <p:column headerText="Eltöltött idő">
                        <h:outputText value="#{worklog.timeSpent}" />
                    </p:column>
                    <p:column headerText="Módosítva">
                        <h:outputText value="#{worklog.updated}">
                            <f:convertDateTime pattern="yyyy.MM.dd HH:mm" />
                        </h:outputText>
                    </p:column>
                </p:dataTable>

            </h:form>
            <p:link id="addWorklog" outcome="newWorklog" value="Worklog hozzáadása">
                <f:param name="issueId" value="#{issueView.issueId}" />
            </p:link>
    </ui:define>
</ui:composition>

src/main/webapp/views/newWorklog.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/default.xhtml">
    <ui:define name="content">
        <div class="jumbotron">
            <h2 class="display-4">Új worklog rögzítése</h2>
        </div>

        <h:panelGroup rendered="#{newWorklogView.messageIsNotEmpty()}">
            <div class="alert alert-danger" role="alert">
                #{newWorklogView.message}
            </div>
        </h:panelGroup>

            <h:form>
            <div style="padding-left: 15px; padding-right: 15px;">
                <div class="row row-border">
                    <div class="col-3">
                        Kezdés:
                    </div>
                    <div class="col">
                        <p:calendar id="datetime" value="#{newWorklogView.worklog.started}" pattern="yyyy/MM/dd HH:mm" />
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Eltöltött idő:
                    </div>
                    <div class="col">
                        <p:inputText value="#{newWorklogView.worklog.timeSpent}" />
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Megjegyzés:
                    </div>
                    <div class="col">
                        <p:inputTextarea rows="10" cols="50" value="#{newWorklogView.worklog.comment}" />
                    </div>
                </div>
            </div>

            <p:commandButton value="Mentés" id="mentes" upldate="@form" actionListener="#{newWorklogView.save}" styleClass="ui-priority-primary" process="loginForm" ajax="false"/>
            </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/views/worklog.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/default.xhtml">
    <ui:define name="content">

        <div class="jumbotron">
            <h2 class="display-4">Worklog részletei</h2>
        </div>

        <h:panelGroup rendered="#{worklogView.messageIsNotEmpty()}">
            <div class="alert alert-danger" role="alert">
                #{worklogView.message}
            </div>
        </h:panelGroup>

            <h:form>
            <div style="padding-left: 15px; padding-right: 15px;">
                <div class="row row-border">
                    <div class="col-3">
                        Szerző:
                    </div>
                    <div class="col">
                        #{worklogView.worklog.author.name}
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Kezdés:
                    </div>
                    <div class="col">
                        <p:calendar id="datetime" value="#{worklogView.worklog.started}" pattern="yyyy/MM/dd HH:mm" />
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Eltöltött idő:
                    </div>
                    <div class="col">
                        <p:inputText value="#{worklogView.worklog.timeSpent}" />
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Módosítva:
                    </div>
                    <div class="col">
                        <h:outputText value="#{worklogView.worklog.updated}">
                            <f:convertDateTime pattern="yyyy.MM.dd HH:mm:ss" />
                        </h:outputText>
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Létrehozva:
                    </div>
                    <div class="col">
                        <h:outputText value="#{worklogView.worklog.created}">
                            <f:convertDateTime pattern="yyyy.MM.dd HH:mm" />
                        </h:outputText>
                    </div>
                </div>
                <div class="row row-border">
                    <div class="col-3">
                        Megjegyzés:
                    </div>
                    <div class="col">
                        <p:inputTextarea rows="10" cols="50" value="#{worklogView.worklog.comment}" />
                    </div>
                </div>
            </div>

            <p:commandButton value="Mentés" id="mentes" upldate="@form" actionListener="#{worklogView.save}" styleClass="ui-priority-primary" process="loginForm" ajax="false"/>
            </h:form>
    </ui:define>
</ui:composition>